# By using https://github.com/google-github-actions/deploy-appengine

name: Deploy to Google App Engine
on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      
      - name: Generate environment variables file
        run: node generate-vars.js "${{ secrets.ENV_VARIABLES }}"
        
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
          
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
