# By using https://github.com/google-github-actions/deploy-appengine

name: Deploy to Google App Engine
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest

    steps:
      - id: secrets
        name: Reading from secret manager
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          secrets: |-
            NAME:projects/schedulebear/secrets/NAME/versions/latest
            REGION:projects/schedulebear/secrets/REGION/versions/latest
            PROJECT_ID:projects/schedulebear/secrets/PROJECT_ID/versions/latest

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Generate environment variables file
        run: node logenv.js "NAME,REGION"
        env:
          NAME: ${{ steps.secrets.outputs.NAME }}
          REGION: ${{ steps.secrets.outputs.REGION }}
      
      - name: List all files
        run: ls -al
      
      - name: List content of environment file generated
        run: cat .env

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml dispatch.yaml
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ steps.secrets.outputs.PROJECT_ID }}


      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
