# By using https://github.com/google-github-actions/deploy-appengine

name: Deploy to Google App Engine
on:
  push:
    branches: [ main ]
  
jobs:
  deploy:
    name: GAE Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.gcp_credentials }}
          
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
